### ISSUE TITLE
MtToEs - Failing to export to ElasticSearch with Connection error 

### ISSUE THREAD

**Issue by EddieLF** [populationgenomics/production-pipelines#1005]
A recent joint callset was created with ~450 WGS samples. After the stages `JointGenotyping`, `AnnotateCohort`, and `AnnotateDataset`, the resulting dataset MatrixTable is exported to the ElasticSearch cluster through the `MtToEs` stage.

Unfortunately, this export seems to be failing consistently, with the same errors. This has been tested with the latest versions of Hail (0.2.133) & cpg_workflows (1.30.4), as well as with the older versions of Hail (0.2.132) and cpg_workflows (1.27.3). Each time, the result is the same error after approximately 6.5 hours (old versions) or 4.5 hours (new versions). 

#### Hail 0.2.132 / cpg_workflows:1.27.3  

- https://batch.hail.populationgenomics.org.au/batches/530245
- https://batch.hail.populationgenomics.org.au/batches/530363
- https://batch.hail.populationgenomics.org.au/batches/530492

#### Hail 0.2.133 / cpg_workflows:1.30.4   

- https://batch.hail.populationgenomics.org.au/batches/530152/jobs/1
- https://batch.hail.populationgenomics.org.au/batches/530152/jobs/1

---

#### Example of successful export

- https://batch.hail.populationgenomics.org.au/batches/530191
In this example, a smaller, ~15gb index was exported successfully in just over 1 hour, using Hail 0.2.133 & cpg_workflows:1.30.5

---

### Error

See the batch links above for the full traceback. It seems to relate to Hail / spark, and py4j, as it reads and exports the MatrixTable to the elasticsearch cluster.

```
hail.utils.java.FatalError: TaskCompletionListenerException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[elasticsearch.es.australia-southeast1.gcp.elastic-cloud.com:9243]] 
```

### Priority and debugging

This is tricky to debug, because:
- A repro test case needs to be very large. The expected size of this elastic index is approximately 500-700gb.
- The hot node, which we write elastic indexes to, needs to be scaled up to accommodate such a large index being written. However, scaling the node up for extended periods is very expensive.
- The error messages and stacktrace don't really offer much substance to explain what could be going wrong.
- The logs saved in the elasticsearch cluster don't have any logging lines relating to the errors. There are lines that show the index writing starts, but no lines to say that it crashed or errored out. The logs in general are quite messy.

### TODO

- [ ] Try exporting another comparably large index from a different dataset, and see if it succeeds
- [ ] Create a thread in Zulip to enlist help from the Hail team
- [ ] Contact elastic co support to try and find out what might be going wrong
